# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-TkBR-OqaXfNeJweR_LeLkWqGjmXeS_b
"""

import streamlit as st
import pysrt
import re
import pickle
import spacy

import nltk
from nltk.corpus import stopwords as nltk_stopwords

# загружаем модель
def load():
    with open('./sgd_model.pcl', 'rb') as fid:
        return pickle.load(fid)

# изображение
st.image('./movie.jpg', caption='Learn with enjoynment')

# заголовок
st.header('Узнай уровень английского в фильме')

#загружаем файл
srt_file = st.file_uploader("Загрузите субтитры в формате SRT:", type="srt")

# PREPROCESSING
# стопслова для английского nltk
nltk.download('stopwords')
stopwords = nltk_stopwords.words('english')

# дополнительные стоп слова
pronouns = ['I', 'me', 'you', 'he', 'she', 'it']
articles = ['a', 'an', 'the']
prepositions = ['in', 'on', 'at', 'by', 'to', 'for', 'from']
conjunctions = ['and', 'but', 'or', 'yet']
interjections = ['oh', 'shh', 'yeah', 'ah', 'uh', 'mmm']

stopwords = stopwords + pronouns + articles + prepositions + conjunctions + interjections

def clean_stopwords(text):
    text = [word for word in text if word not in stopwords]
    return " ".join(text)

# лемматизация
nlp = spacy.load('en_core_web_sm')

def lemmatize_text(text):
    doc = nlp(text)
    lemmas = [token.lemma_ for token in doc]

    return lemmas

# регулярные выражния
HTML = r'<.*?>'  # html tags
TAG = r'{.*?}'  # other tags
COMMENTS = r'[\(\[][A-Za-z ]+[\)\]]'  # comments
UPPER = r'[[A-Za-z ]+[\:\]]'  # speakers names (BOBBY:)
LETTERS = r'[^a-zA-Z\'.,!? ]'  # need only the letters
APOSTROPHES = r' [A-Za-z]+\'[A-Za-z]+ '  # delete words with apostrophes
SPACES = r'([ ])\1+'  # multiple spaces
SYMB = r"[^\w\d'\s]"  # puctuation marks


def clean_text(text):
    """
    убирает все лишние элементы
    """
    # replace with a space
    for element in [HTML, TAG, COMMENTS, UPPER, LETTERS, APOSTROPHES]:
        text = re.sub(element, ' ', text)

        # replace with an empty string
    text = re.sub(SYMB, '', text)
    text = re.sub('www', '', text)
    text = re.sub("''", '', text)

    # spaces
    text = re.sub(SPACES, r'\1', text)

    # delete non-ascii characters
    text = text.encode('ascii', 'ignore').decode()

    text = text.strip()  # delete left and right spaces
    text = text.lower()  # lowercase

    return text

def prepare_srt(srt_file):
    """
    готовит субтитры для молели.
    """
    srt_text = srt_file.read().decode('iso-8859-1')
    subs = pysrt.from_string(srt_text)
    subs = ' '.join([sub.text for sub in subs])
    subs = clean_text(subs)      
    subs = lemmatize_text(subs)  
    subs = clean_stopwords(subs) 

    return subs

if srt_file is not None:
    # препроцессинг
    subs = prepare_srt(srt_file)

    # предсказание
    model = load()
    y_predict = model.predict([subs])

    st.subheader(f'Predicted English level: {y_predict[0]}')